### ISSUE TITLE
Executable file not found

### ISSUE THREAD

**Issue by i-panov** [bazilio91/yii2-stubs-generator#14]
Hi! Thanks for this cool extension! I have been looking for something like that for a long time. Everything works, but there is a problem with File Watcher. I understand of course that this is not your extension, but I hope you will help to solve it.

![28-12-2018 101151](https://user-images.githubusercontent.com/16288735/50506258-28093480-0a89-11e9-8473-b992a318f8e0.png)

I acted according to your instructions, but received an error: File not found. But the file exists! I ran it for generate stubs. Why it happens?

Moreover! When I tried to specify the full path to the file (without using a variable), I received errors:

```
cmd.exe /D /C call C:\OSPanel\domains\my-site.local\yii.bat stubs config/console.php config/web.php
An Error occurred while handling another error:
ReflectionException: Class user does not exist in C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php:428
Stack trace:
#0 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(428): ReflectionClass->__construct('user')
#1 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(364): yii\di\Container->getDependencies('user')
#2 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('user', Array, Array)
#3 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Instance.php(167): yii\di\Container->get('user')
#4 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Instance.php(137): yii\di\Instance->get(NULL)
#5 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\filters\AccessControl.php(102): yii\di\Instance::ensure(Object(yii\di\Instance), 'yii\\web\\User')
#6 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\filters\AccessControl->init()
#7 [internal function]: yii\base\BaseObject->__construct(Array)
#8 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass->newInstanceArgs(Array)
#9 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('yii\\filters\\Acc...', Array, Array)
#10 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('yii\\filters\\Acc...', Array, Array)
#11 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Component.php(191): yii\BaseYii::createObject(Array)
#12 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\BaseYii.php(546): yii\base\Component->__set('access', Array)
#13 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\BaseObject.php(107): yii\BaseYii::configure(Object(bupy7\pages\controllers\ManagerController), Array)
#14 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Controller.php(86): yii\base\BaseObject->__construct(Array)
#15 [internal function]: yii\base\Controller->__construct('manager', Object(bupy7\pages\Module), Array)
#16 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass->newInstanceArgs(Array)
#17 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('bupy7\\pages\\con...', Array, Array)
#18 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('bupy7\\pages\\con...', Array, Array)
#19 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Module.php(583): yii\BaseYii::createObject(Array, Array)
#20 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Module.php(588): yii\base\Module->createController('')
#21 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\UnknownCommandException.php(78): yii\base\Module->createController('manager')
#22 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\ErrorHandler.php(35): yii\console\UnknownCommandException->getSuggestedAlternatives()
#23 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\console\ErrorHandler->renderException(Object(yii\console\UnknownCommandException))
#24 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\console\UnknownCommandException))
#25 {main}

Next yii\base\InvalidConfigException: Failed to instantiate component or class "user". in C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Instance.php:139
Stack trace:
#0 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\filters\AccessControl.php(102): yii\di\Instance::ensure(Object(yii\di\Instance), 'yii\\web\\User')
#1 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\filters\AccessControl->init()
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('yii\\filters\\Acc...', Array, Array)
#5 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('yii\\filters\\Acc...', Array, Array)
#6 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Component.php(191): yii\BaseYii::createObject(Array)
#7 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\BaseYii.php(546): yii\base\Component->__set('access', Array)
#8 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\BaseObject.php(107): yii\BaseYii::configure(Object(bupy7\pages\controllers\ManagerController), Array)
#9 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Controller.php(86): yii\base\BaseObject->__construct(Array)
#10 [internal function]: yii\base\Controller->__construct('manager', Object(bupy7\pages\Module), Array)
#11 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass->newInstanceArgs(Array)
#12 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('bupy7\\pages\\con...', Array, Array)
#13 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('bupy7\\pages\\con...', Array, Array)
#14 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Module.php(583): yii\BaseYii::createObject(Array, Array)
#15 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Module.php(588): yii\base\Module->createController('')
#16 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\UnknownCommandException.php(78): yii\base\Module->createController('manager')
#17 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\ErrorHandler.php(35): yii\console\UnknownCommandException->getSuggestedAlternatives()
#18 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\console\ErrorHandler->renderException(Object(yii\console\UnknownCommandException))
#19 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\console\UnknownCommandException))
#20 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "stubs". in C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('stubs', Array)
#1 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('stubs', Array)
#2 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#3 C:\OSPanel\domains\my-site.local\yii(20): yii\base\Application->run()
#4 {main}

Next yii\console\UnknownCommandException: Unknown command "stubs". in C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\Application.php:183
Stack trace:
#0 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('stubs', Array)
#1 C:\OSPanel\domains\my-site.local\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#2 C:\OSPanel\domains\my-site.local\yii(20): yii\base\Application->run()
#3 {main}

Process finished with exit code 1
```

But in manual mode (through launching `yii stubs` from the console) everything is generated without errors. Help me please!

**Comment by i-panov** [comment]
@bazilio91 No, it still does not work. It seems that in this field variables do not work at all.

**Comment by DBX12** [comment]
Hey folks,
I know this is close to necroposting, but I could solve a similar issue by replacing `$Projectpath$` with `$ProjectFileDir$`.
